### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by Charlie0257** [mahaitongdae/Reachability_Constrained_RL#2]
When I run the following command——
`python train_script.py`

There is an error occurring——
`/home/charlie/PycharmProjects/Reachability_Constrained_RL/safe-control-gym/safe_control_gym/utils/configuration.py:72: UserWarning: No agent/task config given.`
  `warnings.warn("No agent/task config given.")`
`Traceback (most recent call last):`
  `File "/home/charlie/PycharmProjects/Reachability_Constrained_RL/train_scripts/train_script.py", line 309, in <module>`
    `main('RAC')`
  `File "/home/charlie/PycharmProjects/Reachability_Constrained_RL/train_scripts/train_script.py", line 276, in main`
    `args = built_parser(alg_name)`
  `File "/home/charlie/PycharmProjects/Reachability_Constrained_RL/train_scripts/train_script.py", line 250, in built_parser`
    `config = CONFIG_FACTORY.merge()`
  `File "/home/charlie/PycharmProjects/Reachability_Constrained_RL/safe-control-gym/safe_control_gym/utils/configuration.py", line 76, in merge`
    `merge_dict(config_dict, read_file(f))`
  `File "/home/charlie/PycharmProjects/Reachability_Constrained_RL/safe-control-gym/safe_control_gym/utils/utils.py", line 73, in merge_dict`
    `for k, v in update_dict.items():`
`AttributeError: 'NoneType' object has no attribute 'items'`

Could you give me some suggestions for this erorr?
Thanks for any help :)

**Comment by chrismartel** [comment]
Hi @Charlie0257 ,

I am facing the same issue, how did you solve it?
