### ISSUE TITLE
Comparison results between SAC-SI and RAC

### ISSUE THREAD

**Issue by yihangyao** [mahaitongdae/Reachability_Constrained_RL#4]
Dear Haitong,

Thanks for the excellent work and for releasing the code! I read your leading papers in Safe RL: _Reachability Constrained Reinforcement Learning_, and _Learn Zero-Constraint-Violation Policy in Model-Free Constrained Reinforcement Learning_. **I am curious about the comparison results between RAC and SAC-SI in Figure 4 of _Reachability constrained reinforcement Learning_.** Why does SAC-SI perform badly (the cost of SAC-SI converges to a non-zero value) in this case? As far as I know, they both have good theoretical guarantees for constraint satisfaction. Could you please provide more intuition and details about the comparison results? Any help will be highly appreciated!

Thanks for your time and attention!

Best,

Louis

**Comment by mahaitongdae** [comment]
Hi Louis,

Thanks for your interest in our projects! It's a very good question. RAC is a purely data-driven method. SI requires more knowledge of the system, like actuator limits, maximum velocity, probably relative degree of constraint and inputs, etc. If we do not have those, then it is difficult for SI to guarantee safety. This is why SAC-SI is bad in these purely data-driven experiments.

I admit this might not be a fair comparison, but learning CBF/SI for unknown system is also highly nontrivial. There are some recent work using learning-based methods to synthesize SI or CBF. You can also check those papers.

Hope this will help!

Best,
Haitong

**Comment by yihangyao** [comment]
Hi Haitong,

Thanks for your timely and detailed response! Looking forward to more of your interesting and impactful work!

Best,

Louis
