### ISSUE TITLE
about reward shaping

### ISSUE THREAD

**Issue by Tietang999** [mahaitongdae/Reachability_Constrained_RL#5]
Thank you for your excellent paper. I would like to know why reward shaping only supports 0/1 cost.

**Comment by ManUtdMoon** [comment]
Hi,

In CMDP a common choice of constraint value at each step is setting them to be 1/0 (violating constraint or not), so we directly use a weighted violation-or-not in reward function, hoping an agent to avoid violation while collecting rewards. The violation-or-not is extracted from gym in [worker.py](https://github.com/mahaitongdae/Reachability_Constrained_RL/blob/ydj_model_free/worker.py#L239). You can change `constraint_violation` to `constraint_values` and then your constraint-related reward will be continuous.

However, we thought that incorporating constraint into reward requires lots of engineering: (1) use constraint or max(0, constraint); (2) the weight of constraint in reward, etc, which is beyond the scope of this paper. Therefore, we did not put much effort into testing all combinations of reward shaping settings and adopt took a simple one (fixed weight = 0.5, 0/1 constraint). But you can try the setting in which you are interested.

Regards,
Dongjie

**Comment by Tietang999** [comment]
> Thank you for your excellent paper. Thank you for your answer
